CREATE TABLE ISIMLER (ID INT IDENTITY (1,1),ISIM VARCHAR (50))
CREATE TABLE SEHIRLER (ID INT IDENTITY (1,1),SEHIR_ADI VARCHAR (50))

ALTER TABLE ISIMLER ADD ADRES VARCHAR (50)
ALTER TABLE ISIMLER DROP COLUMN ADRES
ALTER TABLE SEHIRLER ALTER COLUMN SEHIR_ADI VARCHAR (60)

INSERT INTO ISIMLER (ISIM) VALUES ('DOÐUKAN')


SELECT * FROM ISIMLER 
DROP TABLE ISIMLER
DROP TABLE SEHIRLER
